export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_CONNECTIONS_PENDING = 'REQUEST_CONNECTIONS_PENDING';
export const REQUEST_CONNECTIONS_SUCCESS = 'REQUEST_CONNECTIONS_SUCCESS';
export const REQUEST_CONNECTIONS_FAILED = 'REQUEST_CONNECTIONS_FAILED';